### ISSUE TITLE
PK Ratio Export to markdown

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/Reporting-Engine#107]
StudyID| Age|    BodyWeight|  ReportCL |PKSimCL| Ratio| 
 -- | --: | --: | --: | --: | --: |
'Vogelstein 1977' | 15 |  77 | 133.98 |  95.369 | 0.71181 |
'Vogelstein 1977' | 15 |  62.5 | 90 | 85.928 |  0.95476 |
'Vogelstein 1977' |  9 |  21.5 |  55.04 | 46.07 | 0.83703 |

GMFE = 1.541860

**Comment by msevestre** [comment]
@pchelle 
Please ensure that numbers are right aligned using the :| format

**Comment by Yuri05** [comment]
Fixed
