### ISSUE TITLE
Error processing observed data from a report configuration plan

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Reporting-Engine#119]
[re_input.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3163201/re_input.zip)

When trying to process attached inputs with RE, we get the error below:
```
>> QualificationWorkflow
Error using loadObservationscsv
Too many input arguments.

Error in QualificationWorkflow (line 68)
        ObservedDataSets(i) =
        loadObservationscsv(ConfigurationPlan.ObservedDataSets{i}.Path,...#

```

**Comment by pchelle** [comment]
[reporting engine output.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3167025/reporting.engine.output.zip)

Works here, I attached the output
