### ISSUE TITLE
Running test cases generates ill formatted graphics or even throws errors

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/Reporting-Engine#124]
I ran the 3 test cases, Aciclovir, Rifampicin, and Theophylline. As recommended, I manually copied the file "content.md" from each test projects "input" directory to "input_re". The Matlab version used was 2018b.

**1. Case Aciclovir:** 
Executing "QualificationWorkflow.m" ran through. However, the plots seem to be extending outside the plot area. I attach the produced plots as an example.
[Tralala.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3171623/Tralala.zip)

**2. Case Rifampicin:** 
The following messages appeared:
Warning: Directory already exists. 
> In QualificationWorkflow (line 14) 
INFO: report-configuration-plan.json was extracted successfully
Warning: Directory already exists. 
> In generateOutputFolders (line 36)
  In QualificationWorkflow (line 22) 
Undefined function or variable 'ObservedDataSets'.

Error in QualificationWorkflow (line 79)
runQualificationWorkflow(WSettings, ConfigurationPlan, TaskList, ObservedDataSets);

**3. Case  Theophylline:**
Not plots were generated, the following messages appeared:
Warning: Directory already exists. 
> In QualificationWorkflow (line 14) 
INFO: report-configuration-plan.json was extracted successfully
Warning: Directory already exists. 
> In generateOutputFolders (line 36)
  In QualificationWorkflow (line 22) 
INFO: Start Workflow:  Project specified workflowTye Qualification mode default 
 System is NOT validated 
 Computer _MyPcName_ (PCWIN64) 
 Reporting Engine version: 2 
 Open Systems Pharmacology Suite version: 7.2 
 Version of SimModel: 2.2 
 SimModelCompName: OSPSuite_SimModelComp.xml 
 Matlab version: 9.5.0.944444 (R2018b) 
 Started by: _myUserId_ 

Initialisation of Theophylline\Henrist oral Hot stage extrusion as table\Henrist oral Hot stage extrusion as table.xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 1. 
 Curves 3 : Data|ObservedData|Undefined|Undefined|Theophylline|% dissolved not found 

Warning: Error in TimeProfile plot 1.
 Curves 3 : Data|ObservedData|Undefined|Undefined|Theophylline|% dissolved not found
 
> In runQualificationWorkflow (line 125)
  In QualificationWorkflow (line 79) 
Initialisation of Theophylline\Kaumeier IV 208 mg fit\Kaumeier IV 208 mg fit.xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 2. 
 Index exceeds array bounds. 

Warning: Error in TimeProfile plot 2.
 Index exceeds array bounds.
 
> In runQualificationWorkflow (line 125)
  In QualificationWorkflow (line 79) 
Initialisation of Theophylline\Kaumeier oral solution 185mg\Kaumeier oral solution 185mg.xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 3. 
 Index exceeds array bounds. 

Warning: Error in TimeProfile plot 3.
 Index exceeds array bounds.
 
> In runQualificationWorkflow (line 125)
  In QualificationWorkflow (line 79)

**Comment by UlrichSi** [comment]
Here are the data directories and the QualificationWorkflow.m. Delete/uncomment the corresponding initialization part. Test 02 is too big to upload.

[01_Aciclovir.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3172496/01_Aciclovir.zip)

[03_Theophylline.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3172498/03_Theophylline.zip)
[QualificationWorkflow.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3172500/QualificationWorkflow.zip)

**Comment by msevestre** [comment]
>  As recommended, I manually copied the file "content.md" from each test projects "input" directory to "input_re". The Matlab version used was 2018b.

This is not the recommended way. User needs to create a `Content` folder with all the content files as per specifications. This will have however no bearings on the error reported


Also let's try to create one issue per project for example otherwise it's very hard to know what is what. I am going to create them 

> 01_Acylcolvir and plot size
=> see #125

Probably the default size of plots in matlab when nothing is provided in the quali plan is too small

> 02

Can you please attach the input folder of the QualificationRunner at least so that I can recreate the content 

see #126 

> 03

see #128

**Comment by msevestre** [comment]
closing this one in favor of split tasks

**Comment by Yuri05** [comment]
Fixed with https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/173
