### ISSUE TITLE
Default plots are too small

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Reporting-Engine#125]

**Comment by msevestre** [comment]
see attached example. The qualification plan has no default size for plots and what Matlab is using by default create plots that are not usable. Let's change those defaults

[01_Aciclovir.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3173450/01_Aciclovir.zip)

[Tralala.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3173451/Tralala.zip)

**Comment by Yuri05** [comment]
fixed via https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/146
