### ISSUE TITLE
Issue running the Rifampicin test case

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Reporting-Engine#126]
The following messages appeared:
Warning: Directory already exists. 
> In QualificationWorkflow (line 14) 
INFO: report-configuration-plan.json was extracted successfully
Warning: Directory already exists. 
> In generateOutputFolders (line 36)
  In QualificationWorkflow (line 22) 
Undefined function or variable 'ObservedDataSets'.

Error in QualificationWorkflow (line 79)
runQualificationWorkflow(WSettings, ConfigurationPlan, TaskList, ObservedDataSets);

**Comment by msevestre** [comment]
@UlrichSi Can you please attach the input folder of the QualificationRunner at least so that I can recreate the content

**Comment by UlrichSi** [comment]
The subdirectory "Input" is used for the QualificationRunner, I have deleted the PK-Sim project file to make it small enough. Hope that helps.
[input.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3173563/input.zip)

**Comment by msevestre** [comment]
yes thanks. The pksim file is not used. Only the snapshot.

**Comment by msevestre** [comment]
I have created the output folder here
https://github.com/msevestre/Rifampicin

**Comment by Yuri05** [comment]
fixed
