### ISSUE TITLE
Matching of Observed data does not work in testandplotObservations() in plotQualificationTimeProfile()

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#127]
The structure "ObservedDataSets" contains the field "outputPathList". The content is the "Name" of the output columns but not the path. Thus, there is no warranty for a match in line 134:

findPathOutputj = contains(Curves.Y,ObservedDataSets(j).outputPathList{k});

Also later in line 154:
errorObs = contains(ObservedDataSets(j).outputPathList{kk}, 'SD');

This even worse as the name 'SD' is also not mandatory!

The pathes for the two columns have to be there instead of the names.

**Comment by sfrechen** [comment]
here for clarification what I mean with "Name" and "Path"

![Unbenannt](https://user-images.githubusercontent.com/26569320/57631823-83534380-75a0-11e9-8ff8-9c9d3dd94f2f.png)

**Comment by sfrechen** [comment]
And an example for a variability column:

![Unbenannt](https://user-images.githubusercontent.com/26569320/57631936-bac1f000-75a0-11e9-8a3e-b4e1b4914032.png)

**Comment by msevestre** [comment]
A few issues here:

1. The paths in the snapshot as provided by @sfrechen are not available in the qualification_plan.
2. The reporting engine will split the path e.g `Midazolam 600mg SD|ObservedData|Peripheral Venous Blood|Plasma|Rifampicin|Conc` into two parts (array of cells)
 - Midazolam 600mg SD
 - Conc

3. PKSim needs to ensure that the csv is always exported with the following format

 - Col1: Time
 - Col2: Concentration [unit]
 - Col3: Error

**Comment by sfrechen** [comment]
PK-Sim can re-produce project files from these json files. So, Qualification Runner / Reporting Engine should do the same!

**Comment by msevestre** [comment]
Snapshot file is not available outside of PK-sim. That's why I have outlined the items above to make sure that we can figure out what is what. 

More specifically, we need to ensure that observed data are always exported in the expected order (T, C, E).
I have already changed the code. Once this is accepted, the rest will follow.

Are you ok with this?

**Comment by sfrechen** [comment]
Well, I am happy with everything that works :-)

**Comment by msevestre** [comment]
Then we have a plan. This will be implemented shortly

**Comment by Yuri05** [comment]
Fixed with past PRs
