### ISSUE TITLE
Issue Running Theophylline

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Reporting-Engine#128]
Not plots were generated, the following messages appeared:
Warning: Directory already exists. 
> In QualificationWorkflow (line 14) 
INFO: report-configuration-plan.json was extracted successfully
Warning: Directory already exists. 
> In generateOutputFolders (line 36)
  In QualificationWorkflow (line 22) 
INFO: Start Workflow:  Project specified workflowTye Qualification mode default 
 System is NOT validated 
 Computer _MyPcName_ (PCWIN64) 
 Reporting Engine version: 2 
 Open Systems Pharmacology Suite version: 7.2 
 Version of SimModel: 2.2 
 SimModelCompName: OSPSuite_SimModelComp.xml 
 Matlab version: 9.5.0.944444 (R2018b) 
 Started by: _myUserId_ 

Initialisation of Theophylline\Henrist oral Hot stage extrusion as table\Henrist oral Hot stage extrusion as table.xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 1. 
 Curves 3 : Data|ObservedData|Undefined|Undefined|Theophylline|% dissolved not found 

Warning: Error in TimeProfile plot 1.
 Curves 3 : Data|ObservedData|Undefined|Undefined|Theophylline|% dissolved not found
 
> In runQualificationWorkflow (line 125)
  In QualificationWorkflow (line 79) 
Initialisation of Theophylline\Kaumeier IV 208 mg fit\Kaumeier IV 208 mg fit.xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 2. 
 Index exceeds array bounds. 

Warning: Error in TimeProfile plot 2.
 Index exceeds array bounds.
 
> In runQualificationWorkflow (line 125)
  In QualificationWorkflow (line 79) 
Initialisation of Theophylline\Kaumeier oral solution 185mg\Kaumeier oral solution 185mg.xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 3. 
 Index exceeds array bounds. 

Warning: Error in TimeProfile plot 3.
 Index exceeds array bounds.
 
> In runQualificationWorkflow (line 125)
  In QualificationWorkflow (line 79) 

[03_Theophylline.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3172498/03_Theophylline.zip)
[QualificationWorkflow.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3172500/QualificationWorkflow.zip)

**Comment by msevestre** [comment]
FYI @UlrichSi

**Comment by msevestre** [comment]
03_Theophyline

There is an error with the file
`"Data|ObservedData|Undefined|Undefined|Theophylline|% dissolved"` does not exist as observed data

This might be an issue in PKSim (if the project was created with an older version or if the observed data was renamed maybe?)

**Comment by msevestre** [comment]
@pchelle Improve errror message to add
1 - OBserved Data Set NAme:
2 - Column name
3 - Full Path as you do already

**Comment by Yuri05** [comment]
@msevestre any progress on this issue?

**Comment by Yuri05** [comment]
Problem with observed dat in the project
