### ISSUE TITLE
runQualificationWorkflow does not accept mass units for dimension amount

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#129]
(though PK-Sim does!)

An error is thrown:

ERROR: Error in TimeProfile plot 1. 
 unknown unit mg for this dimension Amount 

Warning: Error in TimeProfile plot 1.
 unknown unit mg for this dimension Amount

**Comment by msevestre** [comment]
what about the reporting engine and toolbox? As far as I know, the core methods are being used for that

**Comment by sfrechen** [comment]
No idea, but since the plot is accurate in PK-Sim, we should accurately reproduce it!

**Comment by msevestre** [comment]
yeah. However if the core engine does not support it, we might have an issue here. 
@Yuri05 @KatrinCoboeken please feedback

**Comment by msevestre** [comment]
@sfrechen Could you attach an example where the issue arises?

**Comment by msevestre** [comment]
Ok this seems to be an error in the code
@pchelle  Use `unit` to retrieve `dimension` (unit respecting case)

**Comment by Yuri05** [comment]
@msevestre @pchelle This issue is fixed, isn't it?

**Comment by Yuri05** [comment]
fixed
