### ISSUE TITLE
Critical error with GOFMergedPlots (wrong indexing)

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#130]
GOFMergedPlots crash immediately with:
"ERROR: Error in GOFMerged plot 1, Group 1. 
 Input must be a row vector of characters or string scalar. "

At least, I found worng indexing in plotQualificationGOFMerged() line 42.

for j=1:length(Groups(i))

should probably be:

for j=1:length(Groups(i).OutputMappings)

**Comment by msevestre** [comment]
Fixed in #131
