### ISSUE TITLE
No captions / numbering in output for "AllPlots"

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#145]

**Comment by Yuri05** [comment]
Captions will be implemented as following:
* if the _title_ was set in a PK-Sim plot: it will be used as caption
* otherwise (title not set): plot _name_ will be used as caption

Numbering: no numbering will be implemented

**Comment by Yuri05** [comment]
fixed with https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/155
