### ISSUE TITLE
Error in DDIRatio plot

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#157]
ERROR: Error in DDIRatio plot 1. 
 Unrecognized variable name 'Substrate'. 

Warning: Error in DDIRatio plot 1.
 Unrecognized variable name 'Substrate'.
 
> In runQualificationWorkflow (line 353)
  In QualificationWorkflow (line 27)

**Comment by sfrechen** [comment]
Probably Issue is here:
Victim = table2cell(ObservedData(ObservedData.ID==DDIRatios(j).ObservedDataRecordId, {'Substrate', 'RouteSubstrate'}));

**Comment by Yuri05** [comment]
Fixed with https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/165
