### ISSUE TITLE
Error in ComparisonTimeProfile plot

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#159]
ERROR: Error in ComparisonTimeProfile plot 25. 
 Struct contents reference from a non-struct array object. 

Warning: Error in ComparisonTimeProfile plot 25.
 Struct contents reference from a non-struct array object.
 
> In runQualificationWorkflow (line 230)
  In QualificationWorkflow (line 27)

**Comment by Yuri05** [comment]
https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/165
