### ISSUE TITLE
Unknown unit µmol for this dimension Mass 

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#161]
ERROR: Error in TimeProfile plot 64. 
 unknown unit µmol for this dimension Mass 

Warning: Error in TimeProfile plot 64.
 unknown unit µmol for this dimension Mass
 
> In runQualificationWorkflow (line 121)
  In QualificationWorkflow (line 27)

**Comment by Yuri05** [comment]
https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/165
