### ISSUE TITLE
ERROR: Error in TimeProfile plot

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#162]
Initialisation of [..]\Qualification-DDI-CYP3A4\reporting engine input\Midazolam\po 3 mg (solution)\po 3 mg (solution).xml
Number of VariableParameters: 0, with formulas: 0, table parameters: 0
Number of VariableSpecies: 0, with formulas: 0 
ERROR: Error in TimeProfile plot 25. 
 Too many outputs requested.  Most likely cause is missing [] around left hand side that has a comma separated list expansion. 

Warning: Error in TimeProfile plot 25.
 Too many outputs requested.  Most likely cause is missing [] around left hand side that has a comma separated list expansion.
 
> In runQualificationWorkflow (line 121)
  In QualificationWorkflow (line 27)

**Comment by Yuri05** [comment]
https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/165
