### ISSUE TITLE
Subchapter names with same names do override

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#163]
Warning: Directory already exists. 
> In generateOutputFolders (line 36)
  In generateOutputFolders (line 60)
  In generateOutputFolders (line 60)
  In generateOutputFolders (line 60)
  In generateOutputFolders (line 60)
  In initializeQualificationWorkflow (line 37)
  In QualificationWorkflow (line 23)

**Comment by sfrechen** [comment]
and result in error:
ERROR: Error in copying Inputs: 
 Arguments must contain a character vector. 
 Inputs index: 3 
 Input path: D:\Qualification\sfrechen\Qualification-DDI-CYP3A4\re_input\Inputs\Rifampicin\Compound\Rifampicin.md 
 Output path:  

Error using copyfile
Arguments must contain a character vector.

Error in initializeQualificationWorkflow (line 55)
        copyfile(fullfile(REInput_path, ConfigurationPlan.Inputs(i).Path), SectionPath);

Error in QualificationWorkflow (line 23)
[WSettings, ConfigurationPlan, TaskList, ObservedDataSets] = initializeQualificationWorkflow(jsonFile, REInput_path, REOutput_path);

**Comment by Yuri05** [comment]
This should be fixed meanwhile.
@sfrechen Please reopen if you still face this problem
