### ISSUE TITLE
DDI Table columns error

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#164]
Observed AUC Ratio contains Pred/Obs AUC Ratio
Pred/Obs AUC Ration contains Observed AUC Ratio
Predicted CMAX Ratio contains Observed CmaxRatio
Observed CMAX Ratio contains ???
Pred/Obs CMAX Ratio contains ???

**Comment by sfrechen** [comment]
Even worse: 
Observed AUC Ratio contains ???

**Comment by Yuri05** [comment]
fixed with https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/166
