### ISSUE TITLE
LLOQ line not drawn in plots

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/Reporting-Engine#176]
In the theophylline example, the PK-Sim plots contain an LLOQ line. This line is not drawn in the RE plots. The LLOQ value is set to 0.2 mg/L in the experimental data set and might be taken from here, if desired.

**Comment by pchelle** [comment]
So far, the configuration of the experimental data has been: 
Column 1: Time
Column 2: Concentration
Column 3: SD
In order to solve the issue, should we add a 4th column in that configuration which define LLOQ ?

**Comment by msevestre** [comment]
@Yuri05 Good point from @pchelle When we export the obs data to CSV, we loose the information

A 4th column does not make much sense as the LLOQ is global. How can we define some meta data to the data? In theory, we could code it in the header

E.g. 
Time | Output  [mg] %LLOQ=0.5243% | SD  or something like that?

**Comment by pchelle** [comment]
@Yuri05, any update on that ?
Should I start implementing the meta data in the header ?

**Comment by Yuri05** [comment]
@pchelle 
After discussing this with @msevestre : should be implemented like this
If LLOQ is available for observed data set stored in _MyObservedData.csv_, then another csv file called _MyObservedData_**_LLOQ**.csv will be created in the same folder with exactly one number (which is LLOQ for the only output in _MyObservedData.csv_). Would look like this:

| LLOQ|Unit|
|----------|----------|
| Value|unit|

**Comment by pchelle** [comment]
I just added a pull request, let me know if it looks the right way.
Related to the topic, do you want to add the LLOQ to Comparison Time Profiles as well ?

**Comment by pchelle** [comment]
Do you want as well to add the LLOQ in the plot Legend (e.g. caption of the observations - LLOQ) ?

**Comment by msevestre** [comment]
@pchelle We do not do it in PKSim or MoBi at the moment so I would say no
