### ISSUE TITLE
Rerunning RE will append figures instead of overriding previous ones

### ISSUE THREAD

**Issue by UlrichSi** [Open-Systems-Pharmacology/Reporting-Engine#177]
When rerunning an example, the old figures are not overridden but instead new figure files are appended, starting with incrementing the last figure number of the previous run. So, if figures 001 to 003 were previously produced, the new figures are numbered from 004 to 006. 

Use the attached zip files from issues #174 and #175 to reproduce.

@Yuri05 and myself believe that this is **not** a feature.

**Comment by msevestre** [comment]
Agreed. This is a bug The counter should be reset

**Comment by UlrichSi** [comment]
It might be a good idea not only to reset the counter but instead delete the old figures for good. Suppose a revised version of the RE script produces a lower number of figures, older figures will still not be overridden.

**Comment by msevestre** [comment]
agreed. Output folder should be deleted completely
@pchelle Probably easy to do?

**Comment by pchelle** [comment]
Agree, in the initialization function, I can check the presence of the RE output folder, if it is already there, it will be deleted to prevent that.

**Comment by UlrichSi** [comment]
Currently, a warning is displayed that the folder is already present. So, the checking routine should be already in place.

**Comment by Yuri05** [comment]
https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/178

**Comment by UlrichSi** [comment]
One potential pitfall remains: If the figures folder is still open in the file explorer, Matlab cannot remove it and will terminate the script with an error. This might be puzzling for some users.

**Comment by msevestre** [comment]
Nothing we can do about that. The same happen if you open a file in excel
and try to delete it somewhere else

Any suggestions as to what should happen?

**Comment by UlrichSi** [comment]
I guess Matlab is a bit strict on that. If I just look at the directory in the file explorer an delete a file in it with some other program, it usually works.

The only reasonable behavior is to display a better error message to tell the user what he is supposed to do. But let's leave it the way it is and see if you get massacred for the RE by the users. ;-)
