### ISSUE TITLE
Concentration (molar) is shown with unit µg/L

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#181]
Obviously a bug.

However, irrespective of whether it is molar or mass, only "Concentration" should be displayed. No one differentiates here. The unit clarifies anyway.

**Comment by sfrechen** [comment]
![001_plotTimeProfile](https://user-images.githubusercontent.com/26569320/58553155-75dec000-8214-11e9-9886-2320109b101a.png)

**Comment by pchelle** [comment]
For the label, I am currently using as is the Dimension defined by the Configuration Plan Axis setting of the Y axis.
I can add a few lines to flag and keep only the concentration, but it may be better to keep it this way if any user want to use a specific label through the Y-Axis settings. Thoughts ?

**Comment by Yuri05** [comment]
>I can add a few lines to flag and keep only the concentration, but it may be better to keep it this way if any user want to use a specific label through the Y-Axis settings. Thoughts ?

Please keep "Concentration" only.
E.g. you could create a small dictionary where dimensions are matched to axis labels:
* if dimension is in the dictionary: use corresponding label from the dictionary
* if not: use dimension

**Comment by Yuri05** [comment]
fixed with https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/188
