### ISSUE TITLE
Order of sections fully messed up

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#184]

**Comment by Yuri05** [comment]
??

**Comment by sfrechen** [comment]
[output.pdf](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3233263/output.pdf)

**Comment by sfrechen** [comment]
Please compare to section order in qualification plan

**Comment by pchelle** [comment]
Is the issue that the sections are following alphabetical order instead of Id order ?
Then, I can add the Id to the folder name to order them in the right way.

**Comment by msevestre** [comment]
@sfrechen This is very hard to understand what the issue is. No description of issues, one pdf attached. I have no idea what qualification plan you are talking about. 
I would really appreciate if you could be a bit more explicit in the issues you are defining. We are sorry to see issues at the first place, but this is part of the process of developing a tool.

**Comment by Yuri05** [comment]
https://github.com/Open-Systems-Pharmacology/Qualification-DDI-CYP3A4/blob/master/input/master_quali_plan.json

**Comment by Yuri05** [comment]
That should be the corresponding qualification plan

**Comment by Yuri05** [comment]
In the report sections must be ordered as in the report configuration plan (not alphabetically and not by id)

**Comment by msevestre** [comment]
Where is the re_input and re_output?

**Comment by msevestre** [comment]
I cannot solve the issue if I do not have a way to see the re_output (e.g. output from Matlab)

**Comment by pchelle** [comment]
I made an output from the example I have for Qualification-DDI-CYP3A4-master
[re_output.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3234396/re_output.zip)

**Comment by msevestre** [comment]
Ok thanks.

**Comment by msevestre** [comment]
@pchelle This is an issue with the way the re generates the folder. There, the folder structure is lost
![image](https://user-images.githubusercontent.com/1041237/58633678-29988c00-82b7-11e9-953d-eb30c319ce53.png)

compared to 
![image](https://user-images.githubusercontent.com/1041237/58633716-47fe8780-82b7-11e9-9d97-56702c4b7fc1.png)


This should fix the folder structure in the report

**Comment by msevestre** [comment]
IT looks like some \ are replaced with some _ . That's why the folder structure is lost. It used to work a few iterations ago

**Comment by Yuri05** [comment]
fixed
