### ISSUE TITLE
Hierarchy of sections lost

### ISSUE THREAD

**Issue by sfrechen** [Open-Systems-Pharmacology/Reporting-Engine#185]

**Comment by Yuri05** [comment]
please explain what you mean. Is it in the final pdf report or ...?

**Comment by sfrechen** [comment]
[output.pdf](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3233265/output.pdf)

**Comment by msevestre** [comment]
I think this relates to #184

**Comment by Yuri05** [comment]
fixed
