### ISSUE TITLE
TimeProfile Plots from PK-Sim. Log/lin option not taken into consideration

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Reporting-Engine#193]
@pchelle Apparently, when a plot is generated using a linear Y scale, this option is not used in the plot and the plot is created using a log scale

Do you think you can correct the issue today?

Please create a branch of 'develop' now so that we only have this one fix in the PR

**Comment by msevestre** [comment]
This is how the config looks like

```
 "Plot": {
          "Axes": [
            {
              "Unit": "h",
              "Dimension": "Time",
              "Type": "X",
              "GridLines": false,
              "Visible": true,
              "DefaultColor": "#FFFFFF",
              "DefaultLineStyle": "None",
              "Scaling": "Linear",
              "NumberMode": "Normal"
            },
            {
              "Unit": "ng/ml",
              "Dimension": "Concentration (molar)",
              "Type": "Y",
              "GridLines": false,
              "Visible": true,
              "DefaultColor": "#FFFFFF",
              "DefaultLineStyle": "None",
              "Scaling": "Log",
              "NumberMode": "Normal"
            }
          ],
```

When scaling is set to "Linear" the Y axis should be linear

**Comment by Incei** [comment]
@msevestre @Yuri05  I hope you are trying to solve the issue i meant:

Exemple : when a pk-sim simulation has 2 plots per simulations, 1 in linear scale and 1 in log scale: BOTH have to be outputted in the RE, exactly like it is set in pk-sim. 

This is currently not the case and both plots are shown in log scale.

**Comment by msevestre** [comment]
from Ibrahim

Example: when a pk-sim simulation has 2 plots per simulations, 1 in linear scale and 1 in log scale: BOTH have to be outputted in the RE, exactly like it is set in pk-sim.

This is currently not the case and both plots are shown in log scale.

@pchelle This is very urgent. Please fix asap

**Comment by Incei** [comment]
Dear all, i removed the previous comment because after rerunning the qualification procedure, both linear and log plots were correctly created! Many thanks!

**Comment by msevestre** [comment]
@Incei So is this issue a "NON" issue or what? I am confused now

**Comment by msevestre** [comment]
@Incei In another word, should we close this issue?

**Comment by Incei** [comment]
@msevestre  it works now for PK-Sim simulation output plots. 
we can close this issue
