### ISSUE TITLE
Ratio-plots y-axis is constricted

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/Reporting-Engine#200]
The ratio plots y-axis are constricted to 0.4-2.4. Therefore all ratios above or below are not shown. This leads to hiding information in the plot and needs to be fixed asap! :)

@Yuri05

**Comment by pchelle** [comment]
@Incei, to help me fix this bug, could you send a .zip of your reporting engine input ?
Or at least specify if the problem is in the PK ratio or DDI ratio plot ?
Thanks

**Comment by Yuri05** [comment]
PK ratio plots

**Comment by Incei** [comment]
Hi, sorry for the late reply. Indeed its teh pk-ratio plot im referring too. If you need more info please let me know.
