### ISSUE TITLE
change request plot labelling 'plotQualificationGOFMerged.m' 

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/Reporting-Engine#202]
Under '...\Reporting Engine 3.0\code\qualification\plotQualificationGOFMerged.m'

Please adjust the x- and y- lables for the 'Observation vs Prediction Figure' which is currently:

xLabelFinal = getLabelWithUnit('Observed',xAxesOptions.Unit);
yLabelFinal = getLabelWithUnit('Predicted',yAxesOptions.Unit);

to :

xLabelFinal = getLabelWithUnit('Observed plasma concentrations',xAxesOptions.Unit);
yLabelFinal = getLabelWithUnit('Simulated plasma concentrations',yAxesOptions.Unit);

**Comment by msevestre** [comment]
@Incei Are you sure? What if the plot is not using plasma concentration? This would be wrong.

**Comment by Incei** [comment]
Good point. Currently we fit only plasma concentration profiles....what would you suggest? Since we have also units in the label....it is not sufficient to only write Observed..or predicted

**Comment by msevestre** [comment]
@Incei The text 'Observed', 'Predicted' etc.. should be part of the GOF Merged configuration and not hard coded. That's the only way that makes sense

**Comment by Incei** [comment]
Should we then also leave out the units?

**Comment by Incei** [comment]
I just want to prevent questions at the end...that it is unclear what is meant with observed and predicted...
Also, defenitally predicted has to be 'simulated', as with PBPK they are not predictions in GOF

**Comment by Yuri05** [comment]
predicted vs Observed do not have _any_ units, or? It's always a fraction..

**Comment by Incei** [comment]
@Yuri05 they are not ratio's, they are (in usual case) concentrations versus concentrations

**Comment by msevestre** [comment]
I think the unit should come from the plot itself, not the legend.
The label (Observed, Predicted) whatever comes from the config

**Comment by Incei** [comment]
@sfrechen

**Comment by Incei** [comment]
For me, it does not make sense in my opinion to not state what is plotted and still provide some unit. At the end it is all about what is in the output plot and should be meaningfull..

**Comment by msevestre** [comment]
The units are defiend as part of the ploit configuration already so we should not duplicate the info to avoid mistake
A parameter could be "showXUnitOnLabel" or "showYUnitOnLabel"

As a user you would have two new fields to define (and two optional fields)
xLabel: 'Observed plasma concentrations' (in your case)
showXUnitOnLabel (default true)
yLabel: 'Simulated plasma concentrations'
showYUnitOnLabel (default true)

**Comment by sfrechen** [comment]
First of all, I agree with Ibrahim: simulated vs. observed would be more appropriate,

Wrt. to the unit discussion: the things which are plotted are definitely not dimensionless. I do not know how you have set it up. But if you are able to extract a unit, you should be able to extract a dimensiona s well. Unit only does not make sense.

Actually, one could have multiple dimensions in such a plot. What happens then?

**Comment by Yuri05** [comment]
>Wrt. to the unit discussion: the things which are plotted are definitely not dimensionless.

Right. Forget about my previous comment

>one could have multiple dimensions in such a plot. What happens then?

If dimensions are convertible in each other (e.g. molar and mass concentration)-values will be (probably) converted.
If not: will (probably) crash.

**Comment by Incei** [comment]
So will it be possible to change 'predicted' to 'simulated'? 
wrt the units, i would prefer to take it out in case the dimension cannot be put in the label (e.g. ..plasma concentration).

**Comment by sfrechen** [comment]
Ok for me. We can align on that such a plot should only cover one dimension, otherwise multiple plots need to be created. Please implement appropriate error handling in case of violations.

And then: please implement as the x and y label as "**simulated/observed dimension unit**"
No option showXUnitOnLabel or showYUnitOnLabel needed then.

**Comment by pchelle** [comment]
I changed the label of the GOF plot by adding the dimension between observed/simulated and the unit in the last pull request. 
Quid of the residuals ? So far the input was dimensionless, so I assumed (sim-obs)/sim and if there was a unit I assumed sim-obs in that unit. Should I be more specific on the y-label ?
