### ISSUE TITLE
option for no table - only ratioplot in pdf

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/Reporting-Engine#207]
Dear both,

In the created report after qualification runner followed by markdownjoiner:

In the main chapter section (e.g. Chapter 2: Pediatric translation qualification) I have kept out the large table and only published a ratio plot including all compounds. In the subchapters for each specific compound the tables are included.

This can currently be only done when I remove the PKRatioTable.md out of the main chapter folder of the reporting engine output before starting the markdown-joiner.

Im not sure how we can technically handle this, but I am a strong supporter to leave out a huge table in an overview chapter where the key message is given.

@Yuri05 @sfrechen

**Comment by pchelle** [comment]
If I understand correctly this issue, you would like to be able to save the .md table(s) in a different section, correct ?
Then, would it be possible to add an optional section variable (e.g. SectionIdTable ?) in the PK ratio plot definition of the configuration plan ? If the optional section is there, I can save the .md result in that section, if not I'll save it in the same section as the plots, GMFE and other table.

I guess that remark applies as well for DDI Ratios.
