### ISSUE TITLE
Either mean line (linear scale) or range (log scale) are not visible in population plots

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/Reporting-Engine#209]
For all population simulations, when means and percentiles are created:

- In log-y scale the ranges (in grey) are never visible
- In linear-y scale the mean lines are never visible

Hope for asap correction.

**Comment by pchelle** [comment]
@Incei, could you send me a short example with the plots, it will be faster for me to flag and fix the bug this way.
Thanks

**Comment by Yuri05** [comment]
[Example.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3346629/Example.zip)
Example attached:
* In lin scale, range is visible, but not the arithmetic mean
* In log scale: the opposite

![001_plotPopulationTimeProfile](https://user-images.githubusercontent.com/25061876/60453471-8a5a1200-9c31-11e9-8229-763e1eab90f1.png)
![002_plotPopulationTimeProfile](https://user-images.githubusercontent.com/25061876/60453473-8d550280-9c31-11e9-95fb-bd62ddf35703.png)

Compare to original plots in PK-Sim:
![grafik](https://user-images.githubusercontent.com/25061876/60453570-c9886300-9c31-11e9-9637-e8b1cd2e709a.png)
![grafik](https://user-images.githubusercontent.com/25061876/60453598-d4db8e80-9c31-11e9-967b-118d2fe80f34.png)

**Comment by pchelle** [comment]
Thank you for the attachment.
- Not visible mean is hidden by the shaded area. 
- The not visible, range may be caused by a 0 in range time profiles that turns into NaN in the log, so we lose the shaded area.
I will try to fix these bugs as soon as possible and let you know when it is working.

**Comment by Incei** [comment]
Great thanks!
