### ISSUE TITLE
Pediatrics Ratio-plots grouping option (split by color and symbol)

### ISSUE THREAD

**Issue by Incei** [Open-Systems-Pharmacology/Reporting-Engine#220]
Somehow I thought i committed this issue before, but i cannot find it back: 
Currently each AUC or Clerance Ratioplot has only 1 symbol and 1 color for all data.

Please add possibility to create subgroups (milestone 1): We need different symbol and coloring options for pediatrics ratio plots just like the DDI-ratio plots.  (e.g. different symbols for each compound data, and different colors for each study.)

**Comment by pchelle** [comment]
@Yuri05, can we implement an intermediate Groups structure as done for GOF and DDI Ratios to fix this ?
Since PKRatio is very similar to DDI Ratio, could a StartTime and EndTime be expected there as well ?

**Comment by Incei** [comment]
@Yuri05 @pchelle if I may answer: also for AUCtau in pediatric ratio plots we have start end endtimes (unless AUCinf)

**Comment by Yuri05** [comment]
Below how it could look like
@Incei Please check and let me know if ok-then I will adjust examples and qualification plan schema

Questions/Remarks on this:

1. New node `HideArtifacts` was added. With this user can tell to hide some of the artifacts associated with the given plot (has nothing to do with grouping, but with #207)
  * @pchelle This node will be optional (for backwards compatibility). If not there: **all** artifacts (Plot, Table and GMFE) must be created (like at the moment)
  * `HideArtifacts` will be defined also for DDIRatio and other kinds of plots with additional artifatcs
  * @Incei @sfrechen Should we also include `"Plot"` in the list of possible artifacts to be hidden? 
Means: are there any situations where we would need e.g. only PK/DDI-Ratio-_Table_ **without** a plot?
2. Colour/Symbol/Caption are now defined per group.

3. Regarding start/end time:
  * Is it required already in milestones 1 or 2 (has to be implemented in Matlab) or can it wait till Milestone 3 (Implementation in R, availability begin of next year)?
  * Please note: start/endtime will be removed later on from the definition of the qualification plan and must be entered as part of observed data (s. [corresponding issue for DDI ratio plots](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/issues/106))
<details><summary><b>OUTDATED</b></summary>

<pre><code><del>
"PKRatioPlots": [ 
      {
        "Title": "Observed versus Predicted Clearance Ratio",
        "PKParameter": "CL",
        "SectionId": 1,
        "HideArtifacts":["Table", "GMFE"],
        "Groups": [
          {
            "Caption": "Group caption #1",
            "Color": "#000000",
            "Symbol": "Circle",
            "PKRatios": [
              {
                "Project": "Amikacin",
                "Simulation": "Vogelstein#1",
                "Output": "Organism|PeripheralVenousBlood|Amikacin|Plasma (Peripheral Venous Blood)",
                "ObservedData": "PK-Parameter",
                "ObservedDataRecordId": 96,
                "StartTime": 0,
                "EndTime": 122,
                "TimeUnit": "h"
              },
              {
                "Project": "Amikacin",
                "Simulation": "Vogelstein#2",
                "Output": "Organism|PeripheralVenousBlood|Amikacin|Plasma (Peripheral Venous Blood)",
                "ObservedData": "PK-Parameter",
                "ObservedDataRecordId": 97,
                "StartTime": 0,
                "EndTime": 122,
                "TimeUnit": "h"
              }
            ]
          },
          {
            "Caption": "Group caption #2",
            "Color": "#FF0000",
            "Symbol": "Diamond",
            "PKRatios": [
              {
                "Project": "Amikacin",
                "Simulation": "Vogelstein#3",
                "Output": "Organism|PeripheralVenousBlood|Amikacin|Plasma (Peripheral Venous Blood)",
                "ObservedData": "PK-Parameter",
                "ObservedDataRecordId": 98,
                "StartTime": 0,
                "EndTime": 122,
                "TimeUnit": "h"
              }
            ]
          }
        ]
      }
    ]
</del></pre></code>

</details>

**Comment by Yuri05** [comment]
@Incei P.S. 
>Somehow I thought i committed this issue before, but i cannot find it back:

Look for issues over all OSP repositories:
https://github.com/issues?q=is%3Aopen+is%3Aissue+user%3AOpen-Systems-Pharmacology

Then you might find something like this 😆 
https://github.com/Open-Systems-Pharmacology/QualificationPlan/issues/149

**Comment by Incei** [comment]
@Yuri05 @sfrechen @janschlender

_Should we also include "Plot" in the list of possible artifacts to be hidden?
Means: are there any situations where we would need e.g. only PK/DDI-Ratio-Table without a plot?_
**Yes**, ideally we could think of adding the table as appendix chapter.

_Is it required already in milestones 1 or 2 (has to be implemented in Matlab) or can it wait till Milestone 3 (Implementation in R, availability begin of next year)?_
**No** , I am currently simulated in pk-sim the t_end manually, for me therefore less priority and can shift to next year.

**Comment by Yuri05** [comment]
Ok, then it would look like below:

* "_HideArtifacts_" can contain any subset of `{"Table", "GMFE", "Plot"} `(having all 3 would produce nothing in the report, which does not make much sense)
* no start/end times for PK ratios

```
"PKRatioPlots": [ 
      {
        "Title": "Observed versus Predicted Clearance Ratio",
        "PKParameter": "CL",
        "SectionId": 1,
        "HideArtifacts":["Table", "GMFE"],
        "Groups": [
          {
            "Caption": "Group caption #1",
            "Color": "#000000",
            "Symbol": "Circle",
            "PKRatios": [
              {
                "Project": "Amikacin",
                "Simulation": "Vogelstein#1",
                "Output": "Organism|PeripheralVenousBlood|Amikacin|Plasma (Peripheral Venous Blood)",
                "ObservedData": "PK-Parameter",
                "ObservedDataRecordId": 96
              },
              {
                "Project": "Amikacin",
                "Simulation": "Vogelstein#2",
                "Output": "Organism|PeripheralVenousBlood|Amikacin|Plasma (Peripheral Venous Blood)",
                "ObservedData": "PK-Parameter",
                "ObservedDataRecordId": 97
              }
            ]
          },
          {
            "Caption": "Group caption #2",
            "Color": "#FF0000",
            "Symbol": "Diamond",
            "PKRatios": [
              {
                "Project": "Amikacin",
                "Simulation": "Vogelstein#3",
                "Output": "Organism|PeripheralVenousBlood|Amikacin|Plasma (Peripheral Venous Blood)",
                "ObservedData": "PK-Parameter",
                "ObservedDataRecordId": 98
              }
            ]
          }
        ]
      }
    ]
```

**Comment by Incei** [comment]
Fine for me :). How is the sorting happening? Can we decide what comes first (e.g. first plot then table)?

    _no start/end times for PK ratios_
Ok, but only for this year...next year it will be implemented right? :)

**Comment by Yuri05** [comment]
> How is the sorting happening? Can we decide what comes first (e.g. first plot then table)?

Not at the moment...

> Ok, but only for this year...next year it will be implemented right?

yes (if a feature request will be created timely ;))

**Comment by Incei** [comment]
_yes (if a feature request will be created timely ;))_

Done!

**Comment by Yuri05** [comment]
@Incei @sfrechen @msevestre @pchelle 
Thinking about the order: should we define `ShowArtifacts` (or just `Artifacts`) instead of `HideArtifacts`?
Then it would be exactly the parts user would like to see in report **incl. their order**?
E.g. `"Artifacts":["Table", "GMFE", "Plot"]` would create the Table first, then GMFE and then the Plot.

(for now order would be always Plot, Table, GMFE anyway)

**Comment by Incei** [comment]
I was thinking exactly the same. I would then prefer just Artifacts. The current order is fine for me at for now. 
@sfrechen what do you think?

**Comment by sfrechen** [comment]
Only artifacts is good.
Standard order would be for me:
"Artifacts":["Plot", "GMFE", "Table"]

Rather top-down, than bottom up.

**Comment by Incei** [comment]
Currently workaround I'm using is removing or renumbering the markdown files in the output folder before running markdownjoiner.

Regarding the standard order both proposals are fine for me.

**Comment by pchelle** [comment]
Works for me. Top-down seems more intuitive.
Will Artifacts concern only PK Ratios and DDI Ratios plots ? (Maybe GOF Merged since GMFE is also an output ?) or any plot ?

**Comment by Yuri05** [comment]
>Will Artifacts concern only PK Ratios and DDI Ratios plots ? (Maybe GOF Merged since GMFE is also an output ?) or any plot ?

Yep, GOF merged as well.
`"Artifacts"` will be defined as **optional** node. If _not present_: **everything** (Plot, Table, GMFE,..) must be created.

**Comment by Incei** [comment]
> 
> 
> > Will Artifacts concern only PK Ratios and DDI Ratios plots ? (Maybe GOF Merged since GMFE is also an output ?) or any plot ?
> 
> Yep, GOF merged as well.
> `"Artifacts"` will be defined as **optional** node. If _not present_: **everything** (Plot, Table, GMFE,..) must be created.

 If not present: everything in order **(Plot, GMFE, Table)** as Sebastian proposed then right? :)

**Comment by Yuri05** [comment]
>If not present: everything in order (Plot, GMFE, Table) as Sebastian proposed then right? :)

Order will be realized within Milestone 3 (available next year)
