### ISSUE TITLE
Remove all µ characters from Matlab source code

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Reporting-Engine#227]
None-Ascii characters in the source code are not always handled properly by Matlab.
If e.g. I edit **plotQualificationPKRatio.m** and save it after that, it looks like below (and qualification workflows crash consequently).
![grafik](https://user-images.githubusercontent.com/25061876/61779493-14486580-ae01-11e9-80b8-8db154efa5ca.png)

Please replace all occurences of `µ` in the source code with character from its asci code (`char(181)`) e.g like this
`mu = char(181);`
`... [mu,'mol/l']...`  (instead of `... 'µmol/l'...`)

s. example here:

https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox-Core/blob/970fcd890cc563c0656d605b092aa3da682959a3/code/auxiliaries/iniUnitList.m#L99

https://github.com/Open-Systems-Pharmacology/Matlab-Toolbox-Core/blob/970fcd890cc563c0656d605b092aa3da682959a3/code/auxiliaries/iniUnitList.m#L179

**Comment by pchelle** [comment]
I updated the code in PK Ratio to have mu defined (I did not find any other µ in the other functions of qualification).
Should I implement the same feature in other code of src that use µ ?

**Comment by Yuri05** [comment]
>Should I implement the same feature in other code of src that use µ ?

Let's keep it for the moment AS IS.
