### ISSUE TITLE
Encoding problem with observed data

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Reporting-Engine#228]
when executing RE for the input attached, the error below appears
[reporting engine input.zip](https://github.com/Open-Systems-Pharmacology/Reporting-Engine/files/3435054/reporting.engine.input.zip)
```

ERROR: Error in PKRatio plot 1 "Observed versus Predicted Clearance Ratio". 
 In PK Ratio Plot 1, Group 1, Ratio 1, Dimension unknown for Unit "�mol*h/l" in Observed Data Record ID "5301" 
```

the problem are some µ characters in the units saved in PKParameters.csv

**Comment by Yuri05** [comment]
@Incei @AndreDlm @sfrechen FYI

**Comment by Incei** [comment]
As you have found the solution (which works!), could you please implement this in a in-between release? :) This is an annoying bug.

**Comment by Yuri05** [comment]
> As you have found the solution (which works!), could you please implement this in a in-between release? :) This is an annoying bug.

https://github.com/Open-Systems-Pharmacology/Reporting-Engine/pull/229
