### ISSUE TITLE
Update "copy_dci_dll" rake task

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Reporting-Engine#33]
`copy_dci_dll` rake task must be updated to copy only **_DCI/DCI_6.1/ReleaseX64/DCI6_1.dll_** to **_Reporting-Engine/src/lib_** (currently it copies all DLLs found under DCI)

I could not found where the task is defined. 

<img width="601" alt="aufnahme3" src="https://user-images.githubusercontent.com/25061876/34610159-215f8c74-f220-11e7-88ed-6a1fec197ffd.png">

**Comment by msevestre** [comment]
@Yuri05 Why do we have so many DCI dlls? Could we clean that up a bit?
Also why do we have ReleaseX64 again?

**Comment by Yuri05** [comment]
6.1 is the new version compiled with VS2017. Here we need both 32- and 64-bit version (32 for the Toolboxes, 64 for reporting engine)

6.0 was kept just in case (e.g. if a Hotfix for Matlab/R-toolbox needs to be created before 7.3-release) 

>Also why do we have ReleaseX64 again?

could rename the folders to **x86** and **x64**

**Comment by msevestre** [comment]
if a hotfix needs to be issued, this will be off a tagged version that will have the correct DCI. 
I do not see any tagged version however so this needs to be done asap (is this the master version?it should be). Then remove DCI 6.0

**Comment by Yuri05** [comment]
PR in DCI created

**Comment by msevestre** [comment]
Tag in submodule are not required because we always reference a very specific commit. But it does not hurt anyways. If a hotfix is required, for a component using DCI, it will always use the right commit.

In THIS repository however, a tag is missing. If this was released, it should have been tagged

**Comment by msevestre** [comment]
There is a PR for version 2.0. Where should I implement those changes? Should I wait until version 2.0 is merged?

**Comment by msevestre** [comment]
ok starting.  I am going to update the reference to DCI
