### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Reporting-Engine#37]
*Block installation on 32bit systems
*set PlatformProgramFilesFolder = "ProgramFilesFolder"

**Comment by msevestre** [comment]
you mean `ProgramFiles64Folder` right?

**Comment by msevestre** [comment]
actually the variable does not make sense here as the instllation folder is passed by the caller

**Comment by Yuri05** [comment]
If I start MSI in interactive mode and change the default installation folder to **_C:\Program Files\\..._** it still installs into **_C:\Program Files(x86)\\..._**
I was wondering why

**Comment by Yuri05** [comment]
Should we add `Platform="x64" `in the package description?

**Comment by msevestre** [comment]
well because this is a 32 bit installer. I need to specify that it is a x64 bit

**Comment by msevestre** [comment]
>Should we add Platform="x64"in the package description?

yes. However this might not be enough. It seems that we have to add 64bit to EACH file in the setup which is going to be a serious pain. I have to check if this is the case
