### ISSUE TITLE
Wrong installation folder

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Reporting-Engine#4]
Current default location for the installation is _C:\Open Systems Pharmacology\Reporting Engine 1.0_
Should be _C:\Program Files (x86)\Open Systems Pharmacology\Reporting Engine 1.0_

**Comment by msevestre** [comment]
This is by design. The install path is set by the bundle installer. We just specify here the subfolder where this will be installed. This is consistent with all other msi packages

**Comment by Yuri05** [comment]
Means that installation location (if installed stand alone) will differ from the installation location if installed as part of the OSP Suite.
Can we change this?

**Comment by msevestre** [comment]
Not sure. What's the issue with this?

**Comment by msevestre** [comment]
Or we need to create a setup.exe that will specify the default installation's path

**Comment by msevestre** [comment]
I'll look into what I can find

**Comment by msevestre** [comment]
I might be able to set this line here
https://github.com/Open-Systems-Pharmacology/Reporting-Engine/blob/develop/setup/setup.wxs#L49

to another default. That's what is used when the UI is starting...

**Comment by msevestre** [comment]
@Yuri05 We have two options
1: 
Since the installation will probably be scripted when installed using the msi, it should be called like that
```
 msiexec /i "<PATH_TO_MSI>\ReportingEngine.1.0.0.msi" TARGETDIR="C:\Program Files (x86)"
```

or we need to create a bundle setup that will set the TARGETDIR automatically

Let me know

**Comment by Yuri05** [comment]
Option :one: (calling with _TARGETDIR_ argument) should be ok, I think

**Comment by Yuri05** [comment]
ok, closing the issue. Will create a new one in case we need setup.exe
