### ISSUE TITLE
umol unit not read properly from the json file

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/Reporting-Engine#83]
![image](https://user-images.githubusercontent.com/1041237/55804983-817ef780-5aab-11e9-9011-74a2acba0295.png)

**Comment by msevestre** [comment]
FYI @Yuri05

**Comment by pchelle** [comment]
This is the encoding issue we were talking about last Friday.
It appears already when reading the file using the Matlab function fileread.
I will try to fix this with fileread, otherwise I will use another Matlab function.

**Comment by msevestre** [comment]
@pchelle Yes. I just wanted to make sure it was documented otherwise we will forget :)

**Comment by Yuri05** [comment]
```
currentEncoding = slCharacterEncoding;
slCharacterEncoding('UTF-8');
jsonFileContent = fileread(jsonFile);
slCharacterEncoding(currentEncoding);
```
That will do the trick.

**Comment by msevestre** [comment]
Cool. I there a reason why we would not see the encoding at the beginning of the qualification workflow? What about reading other files?

**Comment by Yuri05** [comment]
good question! Apparently readtable must be called with explicite UTF-8 Encoding, otherwise result is corrupted:
`readtable('C:\temp\S1-Results.csv', 'Encoding', 'UTF-8');`

@KatrinCoboeken Are you aware of this???
