### ISSUE TITLE
Qualification plot: DDI Ratio

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/Reporting-Engine#99]
* 2 kinds of plots:
  * Predicted vs Observed
  * Residuals vs Observed (=Predicted/Observed vs Observed)
* Displaying 2-fold range and ["Guest et al."](http://dmd.aspetjournals.org/content/39/2/170) range
* Simulations can be grouped

Predicted vs Observed|Residuals vs Observed
------------------------|-------------------------
<img width="250" src="https://user-images.githubusercontent.com/25061876/48136936-31ec9380-e2a1-11e8-8a12-4600c161f1f5.png">|<img width="250" src="https://user-images.githubusercontent.com/25061876/48136939-344eed80-e2a1-11e8-89db-42051fda371d.png">    

### Example definition in qualification plan:

<img src="https://user-images.githubusercontent.com/25061876/48261322-f677d380-e41e-11e8-8340-713f8228ca4e.png">

* _plotType_  attributes defines which kind of the DDI Ratio plot should be created. Possible values:
  * `predictedVsObserved`
  * `residualsVsObserved`
  * `predictedVsObserved|residualsVsObserved` (:arrow_right: **both** plots must be produced using the same configuration)

* predicted PK parameters are calculated based on the time range `[startTime .. endTime]`. Time ranges can be defined independently for _Simulation_control_ and _Simulation_DDI_

* _PKparameter_ can be:
  * `AUC`
  * `CMAX`
  * `AUC|CMAX` (:arrow_right: **both** _AUCR_ and _CmaxR_ plots must be produced using the same configuration)
    * If one of the experimental values (_AUCR_ **OR** _CmaxR_) is absent in the observed data set: omit the corresponding point in the plot (no warning)
    * If **both** _AUCR_ and _CmaxR_ are absent: warning
    

### Definition in Report configuration: same as in qualification plan 
The only change: _observedDataType_ attribute is removed, because there is no distinction between INTERNAL and EXTERNAL observed data sets anymore, s. #15

**Comment by msevestre** [comment]
@Yuri05 Is this implemented? If yes can you close ? Also other issues? Trying so see what's left to do for the next report. Thanks

**Comment by Yuri05** [comment]
Already implemented. Closing
